langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen2.5:1.5b
      log-requests: true
      log-responses: true

logging:
  level:
    dev:
      langchain4j: DEBUG